_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 2
                - 3
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
B:
    value: 256
T:
    value: 12
grad_accum_steps:
    value: 2
max_lr:
    value: 0.0006
max_steps:
    value: 1500
min_lr:
    value: 5.9999999999999995e-05
run_number:
    value: 2
total_batch_size:
    value: 6144
vocab_size:
    value: 4
warmup_steps:
    value: 1000
